version: '3.8'

services:

    mongodb:
        image: mongo:latest
        container_name: mongo
        logging:
            driver: "none"
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-initialisation.js:/docker-entrypoint-initdb.d/mongo-initialisation.js:ro
    back:
        build:
            dockerfile: Dockerfile
            context: "./backend"
        restart: unless-stopped
        container_name: back
        depends_on:
            - mongodb
        volumes:
            - /app/node_modules
            - ./back:/app
        ports:
            - 3030:3030
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            IP_MONGO: ${IP_MONGO}
            PORT_MONGO: ${PORT_MONGO}