version: '3.8'

services:

    mongodb:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-initialisation.js:/docker-entrypoint-initdb.d/mongo-initialisation.js:ro
    